[package]
name = "memflex"
version = "0.1.0"
edition = "2021"
authors = ["ItsEthra"]
license = "MIT"
repository = "https://github.com/ItsEthra/memflex"

[features]
default = ["std", "internal"]
std = ["alloc"]
alloc = []
internal = []
nightly = []
external = []

[dependencies]
memoffset = "0.6"